# Site configuration

debug: true

title: "Blogs and sites powered by flat files"
description: "Spress is a blog-aware application that transform your plain text files in static sites."
logo: spress-logo.png
copyright_name: Yo! Symfony
copyright_url: http://yosymfony.com

# Data about Spress release
release:
   version: "1.1.0"
   github_url: https://github.com/spress/Spress/
   url_package: https://github.com/spress/Spress/releases/download/v1.1.0/spress.zip
   url_phar: https://github.com/spress/Spress/releases/download/v1.1.0/spress.phar

pre_release:
   version:
   url:

author:
    name: Victor Puertas
    url: http://twitter.com/victorpuertas

    # Social networks
    twitter: spress_cms
    github: https://github.com/spress
    bitbucket:
    facebook:
    linkedin:
    gplus:
    youtube: https://www.youtube.com/user/yosymfony

# Facebook Open Graph
open_graph:
    locale: en_US

# Page menus
top_menu:
    - { name: Home, url: /, site_url: true }
    - { name: Download, url: /download, site_url: true }
    - { name: Docs, url: /docs, site_url: true }
    - { name: Add-ons, icon: fa-cogs, url: /add-ons, site_url: true}
    - { name: Blog, url: /blog, site_url: true }
    - { name: About, url: /about, site_url: true }

bottom_menu:
    - { name: Example, url: https://github.com/yosymfony/Spress-theme-spresso }
    - { name: License: MIT, url: /about/license, site_url: true }
    - { name: About, url: /about, site_url: true }
    - { name: Yo! Symfony, url: http://yosymfony.com, siteUrl: true }

# Comments in posts
comments:
    enabled: true
    disqus_shortname: yosymfony

# Forms
forms:
    addons:
        action_url: http://getsimpleform.com/messages/?form_api_token=3065aa656aabf5ed1c2a9230594ce9f7
        redirect_to: http://spress.yosymfony.com/add-ons/submit/thank-you/

# Google Analytics
google_analytics:
    domain: 
    id: 

# Site validation
google_verify:
bing_verify:

# Posts pagination
paginate: 5
paginate_path: 'blog/page:num'

# Github metadata plugin:
repository: spress/Spress

exclude: [README.md,"theme/", build.xml, composer.json, composer.lock, "assets/css/bootstrap-theme.css", "assets/css/bootstrap.css"]
